name: Skip Workflow

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  skip-workflow:
    runs-on: ubuntu-latest
    
    if: contains(github.event.commits[0].modified[*], 'README.md')

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Not skipped!
